<html>
<body>
Se reportan llamadas a <code>Throwable.initCause()</code> donde un constructor de excepción también toma como argumento una <code>Throwable cause</code>.
<p>En este caso, la llamada <code>initCause()</code> puede eliminarse y su argumento puede añadirse a la llamada al constructor de la excepción.</p>
<p><b>Ejemplo:</b></p>
<pre><code>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error al procesar");
    wrapper.initCause(ex); // Llamada innecesaria a 'Throwable.initCause()'
    throw wrapper;
  }
</code></pre>
<p>Está disponible una corrección rápida para pasar el argumento cause al constructor. Después de aplicar la corrección rápida:</p>
<pre><code>
  try {
      process();
  }
  catch (RuntimeException ex) {
    RuntimeException wrapper = new RuntimeException("Error al procesar", ex);
    throw wrapper;
  }
  </code></pre>
<!-- tooltip end -->
</body>
</html>